### ISSUE TITLE
numList updated to sorted list after function is called

### ISSUE THREAD

**Issue by QWERTY-L** [XavierCodingClub/Green-Github#3]
I tried running the script after completing only the bubble sort algorithm (and not changing any of the other code). I inputted 3, 1, 2. To my surprise, all 3 of the lists were printed sorted:

![image](https://user-images.githubusercontent.com/66786053/98041981-c2a6cd00-1df0-11eb-8a45-c02f68c8c443.png)

This is my code in the algorithms file:

```
def bubbleSort(lst):
    lnt = len(lst)
    for i in range(lnt):
        for j in range(lnt - 1):
            if(lst[j] >  lst[j+1]):
                lst[j], lst[j+1] = lst[j+1], lst[j] #switch j and j + 1
    
    return lst


def insertionSort(lst2):
    return lst2


def selectionSort(lst3):
    return lst3
```

I think there may be a problem with the original code which causes the variable to be modified after the function was called. I edited the code to print numList (the variable storing the original list) before and after the bubble sort function was called. It printed 2, 3, 1 at first and then 1, 2, 3 which seems to confirm my suspicions. Am I doing something wrong or is this a bug in the code?

**Comment by z4ab** [comment]
Yeah so basically, variables could be modified in two ways.
The first is changing the original which i believe is called referencing. In cpp (real programming language 😎 jk), you would need a pointer `*var`.
The second way is to make a copy of that variable with new changes. In cpp, this is the default way of dealing with values.

Python does not allow pointers and every variable is a reference, even when returned from the function (which is sooo annoying).  The way you could get around this is by creating a new list for each function.

I have a pull request for fixing issues in the original which I will update.

**Comment by z4ab** [comment]
Sorry I went into a small rant there. You need to change `return lst` with `return lst.copy()`

**Comment by QWERTY-L** [comment]
I agree that c++ is the superior language, but 

both

```
def bubbleSort(a):
    lst = a
    lnt = len(lst)
    for i in range(lnt):
        for j in range(lnt - 1):
            if(lst[j] >  lst[j+1]):
                lst[j], lst[j+1] = lst[j+1], lst[j] #switch j and j + 1
    return lst
```

and

```
def bubbleSort(lst):
    lnt = len(lst)
    for i in range(lnt):
        for j in range(lnt - 1):
            if(lst[j] >  lst[j+1]):
                lst[j], lst[j+1] = lst[j+1], lst[j] #switch j and j + 1
    return lst.copy()
```

Yield the same result as before. I even changed the "print" lines in numberSort.py to

```
foo = numList
print("Sorted with <sort algo>" + str(algorithms.<sort algo>(foo)))
```

with sort algo as whatever the sorting algorithm was. Nothing changed, I still got [1, 2, 3]

**Comment by QWERTY-L** [comment]
Actually, adding:

`lst = a.copy()`

works. Thanks!
